# Enable USB device susbsytem
CONFIG_USB_DEVICE_STACK_NEXT=y

# CMSIS-DAP
CONFIG_DAP=y
CONFIG_DAP_BACKEND_USB=y

# Serial
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_LINE_CTRL=y

# GPIO
CONFIG_GPIO=y

# Logs
CONFIG_LOG=y

# Don't auto-init CDC-ACM (we do it manually)
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=n
