CONFIG_SHELL=y
CONFIG_CSSE4011=y
CONFIG_CSSE4011_SHELL=y
CONFIG_CSSE4011_SHELL_LED=y
CONFIG_CSSE4011_SHELL_GPIO=y
CONFIG_CSSE4011_SHELL_PWM=y
CONFIG_CSSE4011_SHELL_UART=y
CONFIG_CSSE4011_SHELL_I2C=y
CONFIG_CSSE4011_SHELL_ADC=y
CONFIG_CSSE4011_SHELL_IMU=y
CONFIG_LSM6DSL_TRIGGER_NONE=y
CONFIG_LSM6DSL_ACCEL_ODR=4
CONFIG_LSM6DSL_GYRO_ODR=4
